// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'CHANGE_WITH_PEROSNAL',
    appId: '1:CHANGE_WITH_PEROSNAL:web:6fec25a3ac3b1b08c34df5',
    messagingSenderId: 'CHANGE_WITH_PEROSNAL',
    projectId: 'cd-user-baddies',
    authDomain: 'cd-user-baddies.firebaseapp.com',
    storageBucket: 'cd-user-baddies.appspot.com',
    measurementId: 'G-04TJBQJRVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlXHfaA5U5NtntAhJx5SUx3nSGUorUgD4',
    appId: '1:CHANGE_WITH_PEROSNAL:android:c87b936aa8f473cfc34df5',
    messagingSenderId: 'CHANGE_WITH_PEROSNAL',
    projectId: 'cd-user-baddies',
    storageBucket: 'cd-user-baddies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'CHANGE_WITH_PEROSNAL',
    appId: '1:CHANGE_WITH_PEROSNAL:ios:83753f3fe2b833f2c34df5',
    messagingSenderId: 'CHANGE_WITH_PEROSNAL',
    projectId: 'cd-user-baddies',
    storageBucket: 'cd-user-baddies.appspot.com',
    iosClientId: 'CHANGE_WITH_PEROSNAL-b6u4dm6d9t1066t8ten2rhnsaugqm22h.apps.googleusercontent.com',
    iosBundleId: 'com.example.bizreach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'CHANGE_WITH_PEROSNAL',
    appId: '1:CHANGE_WITH_PEROSNAL:ios:987b35589a5b8440c34df5',
    messagingSenderId: 'CHANGE_WITH_PEROSNAL',
    projectId: 'cd-user-baddies',
    storageBucket: 'cd-user-baddies.appspot.com',
    iosClientId: 'CHANGE_WITH_PEROSNAL-og8afer69k020otkgot6po18ok21som9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bizreach.RunnerTests',
  );
}
